FROM golang:1.19.3-alpine3.15@sha256:3ed44ed6b3ab156cb591b6bae2997a7e7fbb8d2c850ac9e87779b879e317cb23 as builder

WORKDIR /workdir
COPY . /workdir

RUN set -x && \
	apk --no-cache add git gcc libc-dev make

RUN git clone https://github.com/khulnasoft-lab/cfssl_trust.git /etc/cfssl && \
    make clean && \
    make all

FROM alpine:3.11
COPY --from=builder /etc/cfssl /etc/cfssl
COPY --from=builder /workdir/bin/ /usr/bin

EXPOSE 8888

ENTRYPOINT ["cfssl"]
CMD ["--help"]
